export const galleryImages = [
    {
        src: "/images/5_12_2024.jpg",
        alt: "Faheem Ali racing action 1",
        aspect: "aspect-[3/4]",
        title: "AUTODESK INVENTOR",
        slug: "autodesk-inventor",
        description: "Detailed exploration of Autodesk Inventor projects and designs. Showcasing 3D modeling, assembly creation, and mechanical design optimization.",
    },
    {
        src: "/images/aaa.png",
        alt: "Faheem Ali racing action 2",
        aspect: "aspect-[4/3]",
        title: "ANSYS",
        slug: "ansys",
        description: "Advanced simulations and analysis using ANSYS software. Focusing on finite element analysis (FEA) and structural integrity testing.",
    },
    {
        src: "/images/Brotherhood.jpg",
        alt: "Faheem Ali racing action 3",
        aspect: "aspect-[3/4]",
        title: "VOLUNTEER",
        slug: "volunteer",
        description: "Community service and volunteer work experiences. engaging with local communities and contributing to social causes.",
    },
    {
        src: "/images/download (1).jpg",
        alt: "Faheem Ali racing action 4",
        aspect: "aspect-[4/3]",
        title: "PRODUCTION MACHINING",
        slug: "production-machining",
        description: "Hands-on experience with production machining and manufacturing processes. Utilizing lathes, mills, and other industrial equipment.",
    },
    {
        src: "/images/55.jpg",
        alt: "Faheem Ali racing action 5",
        aspect: "aspect-[3/4]",
        title: "RESEARCH",
        slug: "research",
        description: "Academic and practical research initiatives in engineering. Investigating new materials, methodologies, and technological advancements.",
    },
    {
        src: "/images/R.png",
        alt: "Faheem Ali racing action 6",
        aspect: "aspect-[4/3]",
        title: "CLUBS & SOCIETIES",
        slug: "clubs-and-societies",
        description: "Active participation and leadership in university clubs and societies. Organizing events, workshops, and collaborative projects.",
    },
    {
        src: "/images/💻.jpg",
        alt: "Faheem Ali podium 1",
        aspect: "aspect-[3/4]",
        title: "WEB DEVELOPMENT",
        slug: "web-development",
        description: "Full-stack web development projects and portfolio work. Building responsive, dynamic, and user-friendly web applications.",
    },
    {
        src: "/images/Short-Term Achievement.jpg",
        alt: "Faheem Ali podium 2",
        aspect: "aspect-[4/3]",
        title: "EDUCATION",
        slug: "education",
        description: "Academic background, degrees, and certifications. Highlighting major coursework, achievements, and educational milestones.",
    },
    {
        src: "/images/download (4).jpg",
        alt: "Faheem Ali podium 3",
        aspect: "aspect-[3/4]",
        title: "LANGUAGE",
        slug: "language",
        description: "Computer-Aided Design projects showcasing technical skills. Creating precise 2D drafts and complex 3D models for engineering applications.",
    },
    {
        src: "/images/faheem-ali-box.png",
        alt: "Motocross bike",
        aspect: "aspect-[4/3]",
        title: "CFD ANALYSIS",
        slug: "cfd-analysis",
        description: "Computational Fluid Dynamics analysis for aerodynamic optimization. Simulating fluid flow to improve performance and efficiency.",
    },
    {
        src: "/images/faheem-ali-box3.png",
        alt: "Showroom 1",
        aspect: "aspect-[3/4]",
        title: "COMMUNITY SERVICE",
        slug: "community-service",
        description: "Impactful community service initiatives and contributions. dedicated to making a positive difference in the lives of others.",
    },
    {
        src: "/images/faheem-ali-box2.png",
        alt: "Showroom 2",
        aspect: "aspect-[4/3]",
        title: "CNC MACHINING",
        slug: "cnc-machining",
        description: "Precision CNC machining projects and fabrication techniques. Programming and operating CNC machines for high-tolerance parts.",
    },
]
